import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {defaults,presets,presetSettings,type Settings} from './presets';
import {Renderer} from './renderer';
import {exportPNG} from './export';
import './style.css';
import {EffectControl} from './Controls';
function App(){
 const canvas=useRef<HTMLCanvasElement>(null),engine=useRef<Renderer|null>(null),input=useRef<HTMLInputElement>(null),mapInput=useRef<HTMLInputElement>(null),stage=useRef<HTMLDivElement>(null);
 const [s,setS]=useState(defaults),[history,setHistory]=useState<Settings[]>([]),[future,setFuture]=useState<Settings[]>([]),[source,setSource]=useState({name:'Chromatic study.png',width:1400,height:1100,url:''}),[error,setError]=useState(''),[status,setStatus]=useState('Initializing GPU'),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0}),[compare,setCompare]=useState(false),[split,setSplit]=useState(50),[bg,setBg]=useState('checker'),[customBg,setCustomBg]=useState('#474a52'),[mapName,setMapName]=useState(''),[busy,setBusy]=useState(false);
 const [view,setView]=useState({width:800,height:700});
 useEffect(()=>{const observer=new ResizeObserver(entries=>{const box=entries[0].contentRect;setView({width:box.width,height:box.height});});if(stage.current)observer.observe(stage.current);return()=>observer.disconnect();},[]);
 const current=useRef(s);current.current=s;
 const update=(patch:Partial<Settings>)=>{setHistory(h=>[...h.slice(-99),current.current]);setFuture([]);setS({...current.current,...patch});};
 const fit=()=>{setZoom(1);setPan({x:0,y:0});};
 useEffect(()=>{try{const r=new Renderer(canvas.current!);engine.current=r;const demo=document.createElement('canvas');demo.width=1400;demo.height=1100;const c=demo.getContext('2d')!;c.fillStyle='#eee7dc';c.fillRect(210,130,980,840);const g=c.createLinearGradient(250,220,1150,800);g.addColorStop(0,'#e65625');g.addColorStop(.38,'#ffd871');g.addColorStop(.62,'#6e72df');g.addColorStop(1,'#3d267b');c.fillStyle=g;c.beginPath();c.arc(700,550,335,0,Math.PI*2);c.fill();c.fillStyle='#292334';c.font='bold 140px Georgia';c.fillText('FORM',460,600);r.upload(demo);r.upload(demo,true);setSource(v=>({...v,url:demo.toDataURL()}));setStatus('Ready • local processing');}catch(e){setError(String(e));setStatus('GPU unavailable');}return()=>{engine.current?.gl.getExtension('WEBGL_lose_context')?.loseContext();};},[]);
 useEffect(()=>{const id=requestAnimationFrame(()=>{try{const r=engine.current;if(!r)return;const scale=Math.min(1,1600/Math.max(source.width,source.height));r.render(s,source.width,source.height,Math.round(source.width*scale),Math.round(source.height*scale));}catch(e){setError(String(e));}});return()=>cancelAnimationFrame(id);},[s,source]);
 async function load(file:File,map=false){if(busy)return;setError('');setStatus('Decoding image…');try{if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error('Choose a PNG, JPEG, or WebP image.');const bitmap=await createImageBitmap(file,{premultiplyAlpha:map?'none':'premultiply',imageOrientation:'from-image'});const r=engine.current;if(!r)throw Error('GPU renderer is unavailable.');if(Math.max(bitmap.width,bitmap.height)>r.limit){bitmap.close();throw Error(`This GPU supports images up to ${r.limit}px per side. Choose a smaller image; exports are never silently reduced.`);}try{r.upload(bitmap,map);if(map){setMapName(file.name);update({preset:7});}else{const url=URL.createObjectURL(file);setSource(old=>{if(old.url.startsWith('blob:'))URL.revokeObjectURL(old.url);return {name:file.name,width:bitmap.width,height:bitmap.height,url};});fit();}}finally{bitmap.close();}setStatus('Ready • local processing');}catch(e){setError(String(e));setStatus('Upload failed');}}
 function control(key:keyof Settings,label:string,min:number,max:number,unit='',step=1){return <EffectControl settings={s} update={update} id={key} label={label} min={min} max={max} unit={unit} step={step}/>;}
 async function save(){setBusy(true);setError('');setStatus('Rendering full-resolution PNG…');await new Promise(r=>setTimeout(r,40));try{await exportPNG(engine.current!,s,source.width,source.height,source.name);setStatus('Export complete • alpha preserved');}catch(e){setError(String(e));setStatus('Export failed');}finally{setBusy(false);const scale=Math.min(1,1600/Math.max(source.width,source.height));engine.current?.render(s,source.width,source.height,Math.round(source.width*scale),Math.round(source.height*scale));}}
 return <div className={"app"+(busy?" exporting":"")} aria-busy={busy} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(e.dataTransfer.files[0])void load(e.dataTransfer.files[0]);}}><header><div className="brand"><span className="logo">◈</span> Glass Lab <small>IMAGE REFRACTION STUDIO</small></div><span className="privacy"><i/> Everything stays on your device</span><button className="export" disabled={busy||!source.url||!!error} onClick={save}>{busy?'Exporting…':'↗ Export PNG'}</button></header>
 <div className="workspace"><aside className="left"><div className="eyebrow">01 / SOURCE IMAGE</div><button className="source-card" onClick={()=>input.current?.click()}><img src={source.url}/><strong>{source.name}</strong><span>{source.width.toLocaleString()} × {source.height.toLocaleString()} px <b>RGBA</b></span></button><button className="subtle full" onClick={()=>input.current?.click()}>＋ Replace image</button><p className="hint">Drop an image anywhere. Replacing your image retains effect settings.</p><input hidden ref={input} type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{if(e.target.files?.[0])void load(e.target.files[0]);e.target.value='';}}/><div className="section-title"><div className="eyebrow">02 / GLASS LIBRARY</div><span>8 effects</span></div><div className="presets">{presets.map((p,i)=><button className={'preset '+(s.preset===i?'selected':'')} key={p.name} onClick={()=>i===7&&!mapName?mapInput.current?.click():update(presetSettings(i))}><span className={'tile tile'+i}>{p.icon}</span><strong>{p.name}</strong></button>)}</div><div className="map-box"><strong>Make it your own</strong><p>Upload a displacement map. Red shifts X, green shifts Y; mid-gray is neutral.</p><button className="subtle full" onClick={()=>mapInput.current?.click()}>↑ {mapName||'Upload custom map'}</button><input ref={mapInput} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{if(e.target.files?.[0])void load(e.target.files[0],true);e.target.value='';}}/></div><div className="local-note">◉ Browser-powered. Private by design.</div></aside>
 <main><div className="toolbar"><div><button onClick={()=>{setZoom(z=>Math.max(.2,z-.25));}}>−</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(z=>Math.min(5,z+.25))}>＋</button><button onClick={fit}>Fit</button></div><div><button className={compare?'active':''} onClick={()=>setCompare(!compare)}>◐ Compare</button><button title="Undo" disabled={!history.length} onClick={()=>{setFuture(f=>[s,...f]);setS(history.at(-1)!);setHistory(h=>h.slice(0,-1));}}>↶</button><button title="Redo" disabled={!future.length} onClick={()=>{setHistory(h=>[...h,s]);setS(future[0]);setFuture(f=>f.slice(1));}}>↷</button><button onClick={()=>update(presetSettings(s.preset))}>Reset</button></div></div><div ref={stage} className={'stage '+bg} style={{backgroundColor:bg==='custom'?customBg:undefined}} onWheel={e=>setZoom(z=>Math.max(.2,Math.min(5,z-e.deltaY*.001)))} onPointerDown={e=>{if((e.target as HTMLElement).closest('input'))return;const x=e.clientX,y=e.clientY,old=pan;e.currentTarget.setPointerCapture(e.pointerId);const move=(ev:PointerEvent)=>setPan({x:old.x+ev.clientX-x,y:old.y+ev.clientY-y});const end=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',end);};window.addEventListener('pointermove',move);window.addEventListener('pointerup',end);}}><div className="art" style={{width:Math.min(view.width*.8,(view.height-100)*source.width/source.height),aspectRatio:`${source.width}/${source.height}`,transform:`translate(${pan.x}px,${pan.y}px) scale(${zoom})`}}><canvas ref={canvas}/>{compare&&<><img className="original" src={source.url} style={{clipPath:`inset(0 ${100-split}% 0 0)`}}/><div className="divider" style={{left:split+'%'}}><span>↔</span></div><input className="comparison" aria-label="Before and after divider" type="range" min="0" max="100" value={split} onChange={e=>setSplit(+e.target.value)}/><span className="before">ORIGINAL</span><span className="after">GLASS</span></>}</div><div className="canvas-tag">{presets[s.preset].name} glass <span> / LIVE PREVIEW</span></div></div><footer><span role="status" aria-live="polite"><i/> {status}</span><div><span>Background</span><select aria-label="Preview background" value={bg} onChange={e=>setBg(e.target.value)}><option value="checker">Transparency</option><option value="light">Light</option><option value="dark">Dark</option><option value="custom">Custom</option></select>{bg==='custom'&&<input aria-label="Custom background color" type="color" value={customBg} onChange={e=>setCustomBg(e.target.value)}/>}</div></footer>{error&&<div role="alert" className="error">{error}<button onClick={()=>setError('')}>Dismiss</button></div>}</main>
 <aside className="right"><div className="eyebrow">03 / FINE TUNE</div><h2>{presets[s.preset].name} glass <span>↗</span></h2><p className="description">{presets[s.preset].description}</p>{control('strength','Distortion',0,150,'px')}{control('spacing',s.preset===5?'Facet size':s.preset===4?'Ripple spacing':'Pattern spacing',4,400,'px')}{control('rotation','Rotation',0,360,'°')}{s.preset===0&&control('curvature','Ridge curvature',0,100,'%')}{s.preset===4&&<>{control('centerX','Ripple center X',0,100,'%')}{control('centerY','Ripple center Y',0,100,'%')}</>}<div className="rule"/>{control('blur','Softness',0,20,'px',.1)}{control('detail','Surface roughness',0,100,'%')}{control('chroma','Color separation',0,12,'px',.1)}{control('blend','Effect blend',0,100,'%')}<details><summary>Direction & position</summary>{control('x','Horizontal amount',0,200,'%')}{control('y','Vertical amount',0,200,'%')}{control('offsetX','Pattern X offset',-500,500,'px')}{control('offsetY','Pattern Y offset',-500,500,'px')}</details><details open><summary>Procedural seed</summary><div className="seed"><input aria-label="Seed" type="number" min="0" max="999999" value={s.seed} onChange={e=>{const n=e.target.valueAsNumber;if(Number.isFinite(n))update({seed:Math.max(0,Math.min(999999,Math.round(n)))});}}/><button onClick={()=>update({seed:Math.floor(Math.random()*999999)})}>⤨ Randomize</button></div></details><p className="hint">Values in pixels refer to the original image. Double-click any slider to reset it.</p><div className="export-note"><span>EXPORT READY</span><strong>{source.width} × {source.height} px</strong><p>PNG · Original resolution · Transparency preserved</p></div></aside></div></div>;
}
createRoot(document.getElementById('root')!).render(<App/>);



